name: smartpill
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animate_do: ^4.2.0
  flutter_onboarding_slider: ^1.0.11
  lottie: ^3.1.3
  easy_date_timeline: ^2.0.9
  animated_custom_dropdown: ^3.1.1
  dio: ^5.7.0
  shared_preferences: ^2.5.3
  http: ^1.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  network_info_plus: ^6.1.3
  connectivity_plus: ^6.1.3
  wifi_iot: ^0.3.19+2
  flutter_secure_storage: ^9.2.4
  mobile_scanner: ^6.0.6
  animated_text_kit: ^4.2.3
  provider: ^6.1.2
  fl_chart: ^0.70.2
  intl: ^0.19.0
  just_audio: ^0.10.2
  flutter_local_notifications: ^19.2.0
  android_alarm_manager_plus: ^4.0.7
  timezone: ^0.10.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/Lottie/
    - assets/sounds/

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Bold.ttf
        - asset: assets/fonts/Exo-ExtraBold.ttf
        - asset: assets/fonts/Exo-Medium.ttf
        - asset: assets/fonts/Exo-Regular.ttf
        - asset: assets/fonts/Exo-SemiBold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
